"""Constants for the post-DONE branch-and-commit policy (ARCH-015).

Side-effect-free module: every string literal the post_fix_policy
module uses lives here. The policy module body MUST NOT inline
these values — the no-magic-numbers grep test
(:mod:`tests.autofix.cli.test_post_fix_no_magic_numbers`) treats
inline literals as a binding contract violation.

Mirrors the discipline established in
:mod:`autofix.cli.run_constants` and
:mod:`autofix.workflow.verify_constants`.
"""
from __future__ import annotations


# --- Policy enum values ----------------------------------------------------

POST_FIX_WORKING_TREE: str = "working-tree"
POST_FIX_BRANCH: str = "branch"
POST_FIX_BRANCH_PR: str = "branch-pr"

DEFAULT_POST_FIX: str = POST_FIX_WORKING_TREE

ALLOWED_POST_FIX: tuple[str, ...] = (
    POST_FIX_WORKING_TREE,
    POST_FIX_BRANCH,
    POST_FIX_BRANCH_PR,
)


# --- Branch / commit templates ---------------------------------------------

BRANCH_NAME_TEMPLATE: str = "autofix/fixes-{run_id}"
COMMIT_MESSAGE_TITLE_TEMPLATE: str = (
    "autofix: applied {n} fixes (run {run_id})"
)
COMMIT_MESSAGE_BULLET_TEMPLATE: str = "- finding-id: {finding_id}"


# --- Config wiring ---------------------------------------------------------

CONFIG_KEY_POST_FIX: str = "post_fix"


# --- Subprocess argument lists ---------------------------------------------

GH_CLI_BIN: str = "gh"

# `gh pr create` invocation. The `--head`, `--base`, `--title`, and
# `--body` flags are appended at call-time; the literal arg-list
# lives here so the policy module never inlines `"pr"`/`"create"`.
#
# Historically this used `--fill` (auto-populate from the latest
# commit). The fill policy left autofix PRs as a bare commit-message
# subject + a list of opaque finding-ids — reviewers had to open the
# diff to learn anything. The current invocation passes a structured
# title + body assembled by ``_build_pr_body`` that mirrors the
# dynos-work conventions: ``## Summary`` / ``## Findings fixed`` /
# ``## Diff`` / ``## Verify``.
GH_PR_CREATE_BASE_ARGS: tuple[str, ...] = (
    GH_CLI_BIN,
    "pr",
    "create",
)


# --- PR body templates -----------------------------------------------------

PR_BODY_TEMPLATE: str = """\
## Summary

autofix's continuous-crawl applied {n} LLM-generated fix(es) to \
{file_count} file(s) on this branch. All patches passed \
`git apply --check` and the cheap byte-compile VERIFY step \
before being committed.

## Findings fixed

| Finding | File:Lines |
|---|---|
{findings_table}

## Diff

```diff
{diff_block}
```

## Verify

- Branch: `{branch_name}`
- Inspect locally: `git fetch origin && git checkout {branch_name}`
- Each fix was generated by a single \
`autofix.repair.llm_patcher.produce_patch` call against the file at \
the listed line range. The cache envelope at \
`.autofix/cache/llm_patches/{{cache_key}}.json` records the prompt + \
response for each finding.

🤖 Generated by autofix on its own codebase \
(see <https://github.com/dynos-fit/autofix>).
"""

PR_FINDING_ROW_TEMPLATE: str = "| `{rule_id}` | `{path}:{lines}` |"

PR_DIFF_MAX_BYTES: int = 60_000  # leave headroom under GitHub's 65k-char body cap


__all__ = [
    "POST_FIX_WORKING_TREE",
    "POST_FIX_BRANCH",
    "POST_FIX_BRANCH_PR",
    "DEFAULT_POST_FIX",
    "ALLOWED_POST_FIX",
    "BRANCH_NAME_TEMPLATE",
    "COMMIT_MESSAGE_TITLE_TEMPLATE",
    "COMMIT_MESSAGE_BULLET_TEMPLATE",
    "CONFIG_KEY_POST_FIX",
    "GH_CLI_BIN",
    "GH_PR_CREATE_BASE_ARGS",
    "PR_BODY_TEMPLATE",
    "PR_FINDING_ROW_TEMPLATE",
    "PR_DIFF_MAX_BYTES",
]
