"""Content-aware generated detection in ``classify_file``.

When the path-only classifier would return ``FileClass.source`` AND
the caller passes a ``read_head`` callable, ``classify_file`` peeks
at the first 8KB and bumps to ``FileClass.generated`` if a marker
is found. This is the missing wire-up for ``is_generated`` —
before this change, it had zero callers.
"""
from __future__ import annotations

from pathlib import Path

from autofix.crawl.file_classifier import FileClass, classify_file


# ---------------------------------------------------------------------------
# Default (read_head is None) — preserves byte-identical legacy
# ---------------------------------------------------------------------------


def test_no_read_head_keeps_source_classification() -> None:
    """A normal .py file with no read_head supplied → source."""
    assert classify_file(Path("myapp/utils.py")) == FileClass.source


def test_no_read_head_does_not_perform_io(tmp_path: Path) -> None:
    """Non-existent .py path → source. Confirms no IO happens when
    read_head is omitted (the file doesn't exist).
    """
    p = tmp_path / "nonexistent.py"
    assert classify_file(p) == FileClass.source


# ---------------------------------------------------------------------------
# read_head supplied — content-aware bump
# ---------------------------------------------------------------------------


def test_read_head_returning_generated_marker_bumps_to_generated() -> None:
    """A source-shaped path whose head contains ``DO NOT EDIT`` →
    bumped to FileClass.generated.
    """
    def read_head(_p: Path) -> str:
        return "# Generated by Apache Thrift -- DO NOT EDIT.\n\nx = 1\n"

    assert classify_file(Path("myapp/utils.py"), read_head=read_head) == FileClass.generated


def test_read_head_returning_normal_content_stays_source() -> None:
    """Source content with no marker → still source."""
    def read_head(_p: Path) -> str:
        return "def real_code():\n    return 1\n"

    assert classify_file(Path("myapp/utils.py"), read_head=read_head) == FileClass.source


def test_read_head_returning_empty_string_stays_source() -> None:
    """Empty content (e.g. brand-new file) → source, no false-positive."""
    def read_head(_p: Path) -> str:
        return ""

    assert classify_file(Path("myapp/utils.py"), read_head=read_head) == FileClass.source


def test_read_head_only_called_for_source_branch() -> None:
    """A docs file (.md) classifies as docs WITHOUT calling read_head.

    Pinning that the bump is only on the source branch — saves IO
    for files that are already classified by path.
    """
    call_count = {"n": 0}

    def read_head(_p: Path) -> str:
        call_count["n"] += 1
        return ""

    result = classify_file(Path("README.md"), read_head=read_head)
    assert result == FileClass.docs
    assert call_count["n"] == 0, "read_head should NOT be called for non-source paths"


def test_read_head_called_only_once_per_source_path() -> None:
    """The bump path calls read_head exactly once. No accidental
    multiple invocations.
    """
    call_count = {"n": 0}

    def read_head(_p: Path) -> str:
        call_count["n"] += 1
        return "real code"

    classify_file(Path("myapp/utils.py"), read_head=read_head)
    assert call_count["n"] == 1


# ---------------------------------------------------------------------------
# read_head error handling — never raise
# ---------------------------------------------------------------------------


def test_read_head_raising_oserror_falls_back_to_source() -> None:
    """If read_head raises OSError, the result falls back to source —
    no exception propagates to the caller.
    """
    def read_head(_p: Path) -> str:
        raise OSError("simulated permission denied")

    assert classify_file(Path("myapp/utils.py"), read_head=read_head) == FileClass.source


def test_read_head_raising_arbitrary_exception_falls_back_to_source() -> None:
    """The function's never-raise contract holds even if read_head is
    pathologically buggy.
    """
    def read_head(_p: Path) -> str:
        raise RuntimeError("any error")

    assert classify_file(Path("myapp/utils.py"), read_head=read_head) == FileClass.source


# ---------------------------------------------------------------------------
# Existing path-only contract preserved
# ---------------------------------------------------------------------------


def test_existing_console_script_paths_kwarg_still_works() -> None:
    """Adding read_head doesn't affect the console_script_paths
    upgrade path.
    """
    p = Path("myapp/cli_entry.py")
    scripts = frozenset({p})
    assert classify_file(p, console_script_paths=scripts) == FileClass.entrypoint


def test_existing_priority_order_unchanged_for_path_only() -> None:
    """A handful of path-only cases must classify exactly as before."""
    assert classify_file(Path("vendor/lodash/index.py")) == FileClass.vendor
    assert classify_file(Path("__pycache__/foo.cpython.pyc")) == FileClass.cache
    assert classify_file(Path("tests/test_foo.py")) == FileClass.test
    assert classify_file(Path("requirements.txt")) == FileClass.lockfile
